server:
  tomcat:
    accesslog:
      directory: logs/${spring.application.name}
      enabled: true
    basedir: .

spring:
  data:
    mongodb:
      uri: "mongodb://dvm1:13014"

contagio:
  baseUrl: "https://efeu.local:13013"
  authTokenValidInMinutes: "5"
  purgeAfterMinutes: "10"
