server:
  tomcat:
    accesslog:
      directory: logs/${spring.application.name}
      enabled: true
    basedir: .

spring:
  data:
    mongodb:
      uri: "mongodb://dvm1:27017"

contagio:
  baseUrl: "https://www.contagio.de:13013"

  pass:
    resourcesDir: "./passresources"

