management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info,health,loggers,metrics,beans
  health:
    db:
      enabled: false
    mongo:
      enabled: true

server:
  port: 13013
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:certs/contagio.jks
    key-store-password: contagio123
    key-alias: contagio

  tomcat:
    accesslog:
      enabled: true

spring:
  application:
    name: contagio-server
  thymeleaf:
    mode: HTML
  data:
    mongodb:
      uri: "mongodb://dvm1:27017"
      database: contagio
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

contagio:
  baseUrl: "https://www.contagio.de"

  pass:
    teamIdentifier: 4V27BGKSLA
    passTypeId: "pass.de.contagio.stt"
    keystorePassword: "1234"
    organisationName: "Contagio"
    description: "TIL - Dein Pass in die Freiheit"
    logoText: "LOGO_TESTTYPE"
    labelColor: "rgb(5, 175, 190)"
    foregroundColor: "rgb(255, 255, 255)"
    backgroundColor: "rgb(208, 38, 0)"

  sign:
    keyname: "contagiosign"
    password: "contagio"

  users:
    - name: conuser
      password: conuser123
      roles:
        - USER
    - name: conadmin
      password: conadmin123
      roles:
        - USER
        - ADMIN
        - API
    - name: conapi
      password: conapi123
      roles:
        - API

  bpRestapi:
    baseurl: "http://localhost:8080/restapi/api/gy/"
    user: "restapi"
    password: "restapi123$"
