management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info,health,loggers,metrics,beans
  health:
    db:
      enabled: false
    mongo:
      enabled: true

server:
  port: 13013
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:contagio.jks
    key-store-password: contagio123
    key-alias: contagio

  tomcat:
    accesslog:
      enabled: true

spring:
  application:
    name: contagio-server
  thymeleaf:
    mode: HTML
  data:
    mongodb:
      uri: "mongodb://dvm1:27017"
      database: contagio
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB


contagio:
  baseUrl: "https://www.contagio.de"

  pass:
    teamIdentifier: 4V27BGKSLA
    passTypeId: "pass.de.contagio.stt"
    keyName: "pass"
    privateKeyPassword: "1234"
    templateName: "contagio1"
    resourcesDir: "/opt/contagio-server"
    organisationName: "Contagio"
    description: "Contagio - Dein Pass in die Freiheit"
    logoText: "Testen Impfen Machen"

  sign:
    keystore: "/contagio-sign.p12"
    keyname: "contagiosign"
    password: "contagio"

  bpRestapi:
    baseurl: "http://localhost:8080/restapi/api/gy/"
    user: "restapi"
    password: "restapi123$"
