server:
  tomcat:
    accesslog:
      directory: logs/${spring.application.name}
      enabled: true
    basedir: .

spring:
  data:
    mongodb:
      uri: "mongodb://dvm1:13014"

contagio:
  baseUrl: "https://efeu.fritz.box:13013"
